name: Build and push Docker image

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.11.2

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-${{ github.ref_name }}-cache
          key: ${{ runner.os }}-buildx-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref_name }}

      - name: Build and push
        run: |
          make push
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          RELEASE_ID: ${{ github.run_number }}
          GIT_HASH: ${{ github.sha }}
